publications = [
    ("Ballito Fever", "http://ballitofever.mobi"),
    ("Bloem Nuus", "http://www.bloemnuus.mobi/"),
    ("Boland Gazette", "http://www.bolandgazette.mobi"),
    ("Carltonville Herald", "http://www.carletonville.mobi"),
    ("City Vision", "http://www.cityvision.mobi"),
    ("Coastal Weekly", "http://www.coastalweekly.mobi"),
    ("Daily Sun", "http://www.dailysun.mobi"),
    ("Die Son", "http://dieson.mobi/"),
    ("DistriksPos", "http://www.distrikspos.mobi"),
    ("Durban North Fever", "http://www.dnfever.mobi"),
    ("East Griqualand Fever", "http://www.egfever.mobi"),
    ("East London Express", "http://www.eastlondonexpress.mobi"),
    ("Edendale Echo", "http://www.echoedendale.mobi"),
    ("Eden Express", "http://www.edenexpress.mobi"),
    ("Eikestad Nuus", "http://www.eikestadnuus.mobi"),
    ("Express Paper", "http://www.expresspaper.mobi"),
    ("Greytown Gazette", "http://www.greytowngazette.mobi"),
    ("Hammanskraal News", "http://www.hammanskraalnews.mobi"),
    ("Hermanus Times", "http://www.hermanustimes.mobi"),
    ("Hillcrest Fever", "http://www.hillcrestfever.mobi"),
    ("Isolomzi Express", "http://www.isoexpress.mobi"),
    ("Kalahari Bulletin", "http://www.kalaharibulletin.mobi"),
    ("Kroonnuus", "http://www.kroonnuus.mobi"),
    ("Leseding News", "http://www.lesedingnews.mobi"),
    ("Maluti", "http://www.maluti.mobi"),
    ("Maritzburg Echo", "http://www.echopmb.mobi"),
    ("Maritzburg Fever", "http://www.pmbfever.mobi"),
    ("Mthatha Express", "http://www.mthathaexpress.mobi"),
    ("Noordkaap", "http://www.noordkaap.mobi"),
    ("Ons Stad", "http://www.onsstad.mobi"),
    ("Paarl Post", "http://www.paarlpost.mobi"),
    ("Parys Gazette", "http://www.parysgazette.mobi"),
    ("People's Post", "http://www.peoplespost.mobi"),
    ("Polokwane Observer", "http://www.observernews.mobi"),
    ("Port Elizabeth Express", "http://www.peexpress.mobi"),
    ("Potchefstroom Herald", "http://www.potchherald.mobi"),
    ("Sedibengster", "http://www.sedibengster.mobi"),
    ("South Coast Fever", "http://www.southcoastfever.mobi"),
    ("Stranger Weekly", "http://stangerweekly.mobi/"),
    ("Sunshine Coast Express", "http://www.sunshinecoastexpress.mobi"),
    ("Tame Times", "http://www.tametimes.mobi"),
    ("The Witness", "http://www.witnessnews.mobi"),
    ("Tygerburger", "http://www.tygerburger.mobi"),
    ("UD News", "http://www.udnews.mobi"),
    ("Ulundi Fever", "http://www.ulundifever.mobi"),
    ("Upper Coast Fever", "http://www.uppercoastfever.mobi"),
    ("Uvo Lwethu Express", "http://www.uvoexpress.mobi"),
    ("VaalWeekblad", "http://www.vaalweekblad.mobi"),
    ("Vista News", "http://www.vistanews.mobi"),
    ("Vrystaat News", "http://www.vrystaat.mobi"),
    ("Weslander", "http://www.weslander.mobi"),
    ("Worcester Standard", "http://www.wstandard.mobi"),
    ("Zululand Fever", "http://www.zululandfever.mobi"),
    ("Uitenhage Despatch", "http://udnews.mobi/"),
]
