publications = [
    ("Ballito Fever", "http://ballitofever.mobi"),
    ("Bloem Nuus", "http://www.bloemnuus.mobi/"),
    ("Boland Gazette", "http://www.bolandgazette.mobi"),
    ("Parys Gazette", "http://www.parysgazette.mobi"),
    ("Die Son", "http://dieson.mobi/"),
    ("Carltonville Herald", "http://www.carletonville.mobi"),
    ("City Vision", "http://www.cityvision.mobi"),
    ("Daily Sun", "http://www.dailysun.mobi"),
    ("DistriksPos", "http://www.distrikspos.mobi"),
    ("Durban North Fever", "http://www.dnfever.mobi"),
    ("East Griqualand Fever", "http://www.egfever.mobi"),
    ("Edendale Echo", "http://www.echoedendale.mobi"),
    ("Eikestad Nuus", "http://www.eikestadnuus.mobi"),
    ("Hermanus Times", "http://www.hermanustimes.mobi"),
    ("Hillcrest Fever", "http://www.hillcrestfever.mobi"),
    ("Kalahari Bulletin", "http://www.kalaharibulletin.mobi"),
    ("Maritzburg Echo", "http://www.echopmb.mobi"),
    ("Maritzburg Fever", "http://www.pmbfever.mobi"),
    ("Paarl Post", "http://www.paarlpost.mobi"),
    ("People's Post", "http://www.peoplespost.mobi"),
    ("Sedibengster", "http://www.sedibengster.mobi"),
    ("South Coast Fever", "http://www.southcoastfever.mobi"),
    ("Stranger Weekly", "http://stangerweekly.mobi/"),
    ("Worcester Standard", "http://www.wstandard.mobi"),
    ("Tygerburger", "http://www.tygerburger.mobi"),
    ("Ulundi Fever", "http://www.ulundifever.mobi"),
    ("Upper Coast Fever", "http://www.uppercoastfever.mobi"),
    ("VaalWeekblad", "http://www.vaalweekblad.mobi"),
    ("Weslander", "http://www.weslander.mobi"),
]
