publications = [
    ("Business Report", "http://www.iol.co.za/cmlink/1.730910"),
    ("Cape Argus", "http://www.iol.co.za/cmlink/1.1037256"),
    ("Cape Times", "http://www.iol.co.za/cmlink/1.1046095"),
    ("Daily News", "http://www.iol.co.za/cmlink/1.1077761"),
    ("Independent Online (Crime/Courts)", "http://iol.co.za/cmlink/news-crime-courts-category-rss-1.663"),
    ("Independent Online (News Priority)", "http://www.iol.co.za/cmlink/1.640"),
    ("Independent Online (News South Africa)", "http://www.iol.co.za/cmlink/1.623"),
    ("Independent Online (News Mpumalanga)", "http://iol.co.za/cmlink/1.661"),
    ("Independent Online (News Eastern Cape)", "http://iol.co.za/cmlink/1.659"),
    ("Independent Online (News Western Cape)", "http://iol.co.za/cmlink/1.667"),
    ("Independent Online (News Gauteng)", "http://iol.co.za/cmlink/1.666"),
    ("Independent Online (News FreeState)", "http://iol.co.za/cmlink/1.655"),
    ("Independent Online (News Limpopo)", "http://iol.co.za/cmlink/1.660"),
    ("Independent Online (News World)", "http://iol.co.za/cmlink/news-world-category-rss-1.653"),
    ("Independent Online (News North West)", "http://iol.co.za/cmlink/1.658"),
    ("Independent Online (News Northern Cape)", "http://iol.co.za/cmlink/1.657"),
    ("Independent Online (News Mandela)", "http://iol.co.za/cmlink/1.650"),
    ("Independent Online (News Back Page)", "http://iol.co.za/cmlink/news-back-page-category-rss-1.652"),
    ("Independent Online (News Mandela2)", "http://iol.co.za/cmlink/1.651"),
    ("Independent Online (Business Watch)", "http://iol.co.za/cmlink/1.688684"),
]
