publications = [
    ("Business Report", "http://www.iol.co.za/cmlink/1.730910"),
    ("Cape Argus", "http://www.iol.co.za/cmlink/1.1037256"),
    ("Cape Times", "http://www.iol.co.za/cmlink/1.1046095"),
    ("Daily News", "http://www.iol.co.za/cmlink/1.1077761"),
    ("Independent Online (Crime/Courts)", "http://iol.co.za/cmlink/news-crime-courts-category-rss-1.663"),
    ("Independent Online (News Priority)", "http://www.iol.co.za/cmlink/1.640"),
    ("Independent Online (News South Africa)", "http://www.iol.co.za/cmlink/1.623"),
    ("Independent Online (News Mpumalanga)", "http://iol.co.za/cmlink/1.661"),
    ("Independent Online (News Eastern Cape)", "http://iol.co.za/cmlink/1.659"),
    ("Independent Online (News Western Cape)", "http://iol.co.za/cmlink/1.667"),
    ("Independent Online (News Gauteng)", "http://iol.co.za/cmlink/1.666"),
    ("Independent Online (News FreeState)", "http://iol.co.za/cmlink/1.655"),
    ("Independent Online (News Limpopo)", "http://iol.co.za/cmlink/1.660"),
    ("Independent Online (News World)", "http://iol.co.za/cmlink/news-world-category-rss-1.653"),
    ("Independent Online (News North West)", "http://iol.co.za/cmlink/1.658"),
    ("Independent Online (News Northern Cape)", "http://iol.co.za/cmlink/1.657"),
    ("Independent Online (News Mandela)", "http://iol.co.za/cmlink/1.650"),
    ("Independent Online (News Back Page)", "http://iol.co.za/cmlink/news-back-page-category-rss-1.652"),
    ("Independent Online (News Mandela2)", "http://iol.co.za/cmlink/1.651"),
    ("Independent Online (Business Watch)", "http://iol.co.za/cmlink/1.688684"),
    ("Pretoria News", "http://www.iol.co.za/cmlink/1.1118954"),
    ("Sunday Tribune (Home Page)", "http://www.iol.co.za/cmlink/home-page-rss-1.1538217"),
    ("Sunday Tribune (TV Box Teaser)", "http://www.iol.co.za/cmlink/tv-box-teaser-rss-1.1537631"),
    ("Sunday Tribune (Editors Pick)", "http://www.iol.co.za/cmlink/editors-pick-extended-rss-1.1137157"),
    ("Sunday Tribune (News Africa Extended)", "http://www.iol.co.za/cmlink/news-africa-extended-1.679216"),
    ("Sunday Tribune (Soccer Extended)", "http://www.iol.co.za/cmlink/soccer-soccer-extended-rss-1.679215"),
    ("Sunday Tribune (Most commented stories)", "http://www.iol.co.za/cmlink/most-commmented-stories-1.1625"),
    ("Sunday Tribune (Most viewed stories)", "http://www.iol.co.za/cmlink/most-viewed-stories-1.1624"),
    ("Sunday Tribune (Back page extended)", "http://www.iol.co.za/cmlink/news-back-page-extended-1.628990"),
    ("Sunday Tribune (News South Africa extended)", "http://www.iol.co.za/cmlink/news-south-africa-extended-1.679178"),
    ("Sunday Tribune (Western Cape extended)", "http://www.iol.co.za/cmlink/western-cape-extended-1.679223"),
    ("Sunday Tribune (Gauteng extended)", "http://www.iol.co.za/cmlink/news-gauteng-extended-1.679235"),
    ("Sunday Tribune (KZN extended)", "http://www.iol.co.za/cmlink/news-kwazulu-natal-extended-1.679236"),
    ("Pretoria Anene Booysen", "http://www.iol.co.za/cmlink/anene-booysen-1.1468146"),
    ("Pretoria Lance Armstrong Hot Topic feed", "http://www.iol.co.za/cmlink/lance-armstrong-hot-topic-feed-1.1454231"),
    ("Pretoria US Elections 2012 RSS feed", "http://www.iol.co.za/cmlink/us-elections-2012-rss-feed-1.1417822"),
    ("Pretoria Malema RSS FEED", "http://www.iol.co.za/cmlink/malema-rss-feed-1.1390238"),
    ("Pretoria Dewani RSS feed", "http://www.iol.co.za/cmlink/dewani-rss-feed-1.1376644"),
    ("Pretoria Home Page Extended", "http://www.iol.co.za/cmlink/home-page-extended-1.628986"),
    ("Pretoria Sport Extended", "http://www.iol.co.za/cmlink/sport-extended-1.628987"),
    ("Pretoria Sport Rugby Extended", "http://www.iol.co.za/cmlink/sport-rugby-extended-1.628988"),
    ("Pretoria Sport Cricket Extended", "http://www.iol.co.za/cmlink/sport-cricket-extended-1.628989"),
    ("Pretoria News World Extended", "http://www.iol.co.za/cmlink/news-world-extended-1.679217"),
    ("Pretoria Sport Golf Extended", "http://www.iol.co.za/cmlink/sport-golf-extended-1.679220"),
    ("The Mercury - Marikana feed", "http://www.iol.co.za/cmlink/marikana-feed-1.1376639"),
    ("The Mercury - The Mercury Editors Note RSS", "http://www.iol.co.za/cmlink/the-mercury-editors-note-rss-1.1264095"),
    ("The Mercury - The Mercury - The Idler RSS", "http://www.iol.co.za/cmlink/the-mercury-the-idler-rss-1.1219266"),
]
