publications = [
    ("Ballito News", "http://www.ballitonews.co.za/feed/"),
    ("Daily Dispatch", "http://www.dispatch.co.za/feed/"),
    ("Daily Dispatch - Politics", "http://www.dispatch.co.za/category/politics/feed/"),
    ("Daily Dispatch - Business", "http://www.dispatch.co.za/category/business-2/feed/"),
    ("Daily Dispatch - Opinion", "http://www.dispatch.co.za/category/opinion/feed/"),
    ("Daily Dispatch - Sport", "http://www.dispatch.co.za/category/sport/feed/"),
    ("Matimu News", "http://matimunews.co.za/?feed=rss2"),
    ("Public Eye News", "http://www.publiceyenews.com/site/feed/"),
    ("The Gremlin", "http://feeds.feedburner.com/co/JdcP?format=xml"),
    ("The Newspaper", "http://www.thenewspaper.co.za/feed/"),
    ("The SA News", "http://www.thesanews.co.za/feed/"),
    ("IQ4 News", "http://www.iq4news.com/rss.xml"),
    ("Klerksdorp Record", "http://www.northwestnewspapers.co.za/klerksdorprecord/index.php?format=feed&type=rss"),
    ("Rise 'n Shine", "http://www.rise-n-shine.co.za/index.php?option=com_content&view=category&layout=blog&id=1&Itemid=50&format=feed&type=rss"),
    ("Cape Business News", "http://www.cbn.co.za/feed/rss/news?format=feed"),
    ("Franco - SA", "http://www.franco-sa.co.za/feed"),
]
