publications = [
    ("African Reporter", "http://africanreporter.co.za/feed/"), 
    ("Alberton Record", "http://albertonrecord.co.za/feed/"), 
    ("Alex News", "http://alexnews.co.za/feed/"), 
    ("Barbeton Times", "http://barbetontimes.co.za/feed/"), 
    ("Bedfordview and Edenvale News", "http://bedfordviewedenvalenews.co.za/feed/"), 
    ("Benoni City Times", "http://benonicitytimes.co.za/feed/"), 
    ("Berea Mail", "http://bereamail.co.za/feed/"), 
    ("Boksburg Advertiser", "http://boksburgadvertiser.co.za/feed/"), 
    ("Brakpan Herald", "http://brakpanherald.co.za/feed/"), 
    ("Camaro Chronicle", "http://comarochronicle.co.za/feed"), 
    ("Capricorn Review", "http://capricornreview.co.za/feed/"), 
    ("Centurion Rekord", "http://rekordcenturion.co.za/feed/"), 
    ("City Buzz", "http://citybuzz.co.za/feed/"), 
    ("Corridor Gazette", "http://corridorgazette.co.za/feed/"), 
    ("Diepkloof Urban News", "http://diepkloofurbannews.co.za/feed"), 
    ("Dobsonville Urban News", "http://urbannews.co.za/feed"), 
    ("Eldorado Urban News", "http://eldoradourbannews.co.za/feed"), 
    ("Estcourt and Midlands News", "http://estcourtnews.co.za/feed/"), 
    ("Eyethu News KZN", "http://eyethunews.co.za/feed/"), 
    ("Fourways Review", "http://fourwaysreview.co.za/feed/"), 
    ("Germiston City News", "http://germistoncitynews.co.za/feed/"), 
    ("Hazyview Herald", "http://hazyviewherald.co.za/feed/"), 
    ("Highvelder", "http://highvelder.co.za/feed/"), 
    ("Highway Mail", "http://highwaymail.co.za/feed/"), 
    ("Jabavu Urban News", "http://jabavuurbannews.co.za/feed"), 
    ("Joburg East Express", "http://joburgeastexpress.co.za/feed"), 
    ("Kempton Express", "http://kemptonexpress.co.za/feed/"), 
    ("Krugersdorp News", "http://krugersdorpnews.co.za/feed/"), 
    ("Ladysmith Gazette", "http://ladysmithgazette.co.za/feed/"), 
    ("Lowvelder", "http://lowvelder.co.za/category/feed/"), 
    ("Lowvelder", "http://lowvelder.co.za/feed/"), 
    ("Makhado Review", "http://makhadoreview.co.za/feed/"), 
    ("Maritzburg Sun", "http://maritzburgsun.co.za/feed/"), 
    ("Meadowlands Urban News", "http://meadowlandsurbannews.co.za/feed/"), 
    ("Midrand Reporter", "http://midrandreporter.co.za/feed/"), 
    ("Mpulanga News", "http://mpumalanganews.co.za/feed/"), 
    ("Nelspruit Post", "http://nelspruitpost.co.za/feed/"), 
    ("Newcastle Advertiser", "http://newcastleadvertiser.co.za/feed/"), 
    ("Northcliffe Melville Times", "http://northcliffmelvilletimes.co.za/feed/"), 
    ("Northeastern Tribune", "http://northeasterntribune.co.za/feed/"), 
    ("North Glen News", "http://northglennews.co.za/feed/"), 
    ("Orlando Urban News", "http://orlandourbannews.co.za/feed/"), 
    ("Pimville Urban News", "http://pimvilleurbannews.co.za/feed/"), 
    ("Polokwane Express", "http://polokwaneexpress.co.za/feed/"), 
    ("Pretoria East Rekord", "http://rekordeast.co.za/feed/"), 
    ("Pretorial East Rekord", "http://rekordeast.co.za/feed/"), 
    ("Pretoria Moot Record", "http://rekordmoot.co.za/feed/"), 
    ("Pretoria North Rekord", "http://rekordnorth.co.za/feed/"), 
    ("Protea Urban News", "http://proteaurbannews.co.za/feed/"), 
    ("Public Eye Maritzburg", "http://publiceyemaritzburg.co.za/feed/"), 
    ("Randburg Sun", "http://randburgsun.co.za/feed/"), 
    ("Randfontein Herald", "http://randfonteinherald.co.za/feed/"), 
    ("Review Bosveld", "http://reviewbosveld.co.za/feed/"), 
    ("Review Online", "http://reviewonline.co.za/feed/"), 
    ("Ridge Times", "http://ridgetimes.co.za/feed/"), 
    ("Roodepoort Northsider", "http://roodepoortnorthsider.co.za/feed/"), 
    ("Roodepoort Record", "http://roodepoortrecord.co.za/feed/"), 
    ("Roodeport Northsider", "http://roodepoortnorthsider.co.za/feed/"), 
    ("Rosebank Killarney Gazette", "http://rosebankkillarneygazette.co.za/feed/"), 
    ("Sandton Chronicle", "http://sandtonchronicle.co.za/feed/"), 
    ("South Coast Herald", "http://southcoastherald.co.za/feed/"), 
    ("Southern Courier", "http://southerncourier.co.za/feed/"), 
    ("Springs Advertiser", "http://springsadvertiser.co.za/feed/"), 
    ("Standardton Advertiser", "http://standertonadvertiser.co.za/feed/"), 
    ("Standerton Advertiser", "http://standertonadvertiser.co.za/feed/"), 
    ("Steelburger Nuus", "http://nelspruitpost.co.za/feed/"), 
    ("Streek News", "http://streeknuus.co.za/feed/"), 
    ("Streeknuus", "http://streeknuus.co.za/feed/"), 
    ("Th Citizen", "http://citizen.co.za/feed/"), 
    ("The Citizen", "http://citizen.co.za/feed/"), 
    ("The Tembisan", "http://tembisan.co.za/feed/"), 
    ("The White River Post", "http://whiteriverpost.co.za/feed/"), 
    ("Vryheid Herald", "http://vryheidherald.co.za/feed/"), 
    ("West Side Urban", "http://westsideurbannews.co.za/feed/"), 
    ("Zola Urban News", "http://zolaurbannews.co.za/feed/"), 
    ("Zululand Observer", "http://zululandobserver.co.za/feed/"), 
]
