publications = [
    ("African Reporter", "http://africanreporter.co.za/feed/"),
    ("Bedfordview and Edenvale News", "http://bedfordviewedenvalenews.co.za/feed/"),
    ("Benoni City Times", "http://benonicitytimes.co.za/feed/"),
    ("Berea Mail", "http://bereamail.co.za/feed/"),
    ("Brakpan Herald", "http://brakpanherald.co.za/feed/"),
    ("Estcourt and Midlands News", "http://estcourtnews.co.za/feed/"),
    ("Fourways Review", "http://fourwaysreview.co.za/feed/"),
    ("Highvelder", "http://highvelder.co.za/feed/"),
    ("Highway Mail", "http://highwaymail.co.za/feed/"),
    ("Kempton Express", "http://kemptonexpress.co.za/feed/"),
    ("Lowvelder", "http://lowvelder.co.za/feed/"),
    ("North Glen News", "http://northglennews.co.za/feed/"),
    ("Randfontein Herald", "http://randfonteinherald.co.za/feed/"),
    ("Pretorial East Rekord", "http://rekordeast.co.za/feed/"),
    ("Ridge Times", "http://ridgetimes.co.za/feed/"),
    ("Roodepoort Record", "http://roodepoortrecord.co.za/feed/"),
    ("Roodepoort Northsider", "http://roodepoortnorthsider.co.za/feed/"),
    ("Springs Advertiser", "http://springsadvertiser.co.za/feed/"),
    ("Standerton Advertiser", "http://standertonadvertiser.co.za/feed/"),
    ("Streek News", "http://streeknuus.co.za/feed/"),
    ("The Citizen", "http://citizen.co.za/feed/"),
    ("The Tembisan", "http://tembisan.co.za/feed/"),
    ("Zululand Observer", "http://zululandobserver.co.za/feed/"),
]
